api_platform:
    defaults:
        pagination_client_items_per_page: true
        pagination_items_per_page: 10
        pagination_maximum_items_per_page: 100
    version: '1.0.0'
    show_webby: true
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
    patch_formats:
        json:
            mime_types: ['application/json']
    formats:
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']
    enable_swagger: true
    enable_swagger_ui: true
    swagger:
        versions: [3]
        api_keys:
            JWT:
                name: Authorization
                type: header
    collection:
        pagination:
            items_per_page_parameter_name: perPage
            page_parameter_name: page
